### ISSUE TITLE
Entity의 Embedded 객체 중복 컬럼 이슈

### ISSUE THREAD

**Issue by TonyKim9401** [KATJ-HH2/katj#92]
## 버그 설명

[버그에 대한 명확하고 간결한 설명]
taxi, taxi_driver, trip 관련 코드 pull 이후 테스트 코드 확인시 오류 발생

## 재현 단계

[버그를 재현하기 위한 단계]
하나의 테이블에 필드 명은 다르지만 같은 Embedable 클래스 사용시 컬럼명 중복 오류 발생
![스크린샷 2023-10-11 오전 2 25 21](https://github.com/KATJ-HH2/katj/assets/87371627/b4427f83-bcde-411f-b228-ef7dd7b14429)

## 예상 동작

[예상했던 동작과 실제 동작의 차이]
같은 객체를 쓰더라도 필드명에 따라 따로 쓸 수 있을거라 예상함
RoadAddress 자체를 departure / destination에 맞추어 나누어야할것으로 협의, 기훈/현준

**Comment by TonyKim9401** [comment]
![image](https://github.com/KATJ-HH2/katj/assets/87371627/029eccb6-644a-4f5a-bc64-d2db0a3cb340)
RoadAddress 하나만 있으면 정상 동작 확인

**Comment by TonyKim9401** [comment]
![image](https://github.com/KATJ-HH2/katj/assets/87371627/b9a3386d-f2ac-4da5-bed7-795d00343da1)
RoadAddress를 둘로 분리하여 컬럼명을 바꿔 문제 해결

**Comment by jiseongTak** [comment]
@AttributeOverrides를  쓰는 방법도 있네요  https://living-only-today.tistory.com/261

**Comment by JangHyeonJun2** [comment]
> @AttributeOverrides를 쓰는 방법도 있네요 https://living-only-today.tistory.com/261

오 요것도 괜찮아보이네요? 
굳이 재정의할 필요가 없으니 수고가 덜겠군요. @TonyKim9401

**Comment by TonyKim9401** [comment]
음 근데 RoadAddress가 사용되는곳이 한두군데가 아니라 재활용성을 생각하면 나눠서 만드는게 나을것같은 생각도 드네요. 지금 당장 재활용 할것 같지는 않지만요 ㅎㅎ 어제 재정의해서 dev에 올려두긴 했습니다!

**Comment by TonyKim9401** [comment]
![image](https://github.com/KATJ-HH2/katj/assets/87371627/9cdf69d9-ffb6-4094-a416-d39540a81b19)
@jiseongTak @JangHyeonJun2 @Yoojin-An 

어제 임시로 만들어 뒀던 departure/destination roadaddress 삭제 후
Trip 테이블의 RoadAddress에 @AttributeOverrides 적용 결과입니다!

**Comment by TonyKim9401** [comment]
![image](https://github.com/KATJ-HH2/katj/assets/87371627/588cfff0-ebf1-409e-8b7b-9cb23880048c)

허재 코치님께 문의 드렸고 답변에 따라 다시 두가지로 선언하였습니다
