### ISSUE TITLE
test-container 적용 예외

### ISSUE THREAD

**Issue by TonyKim9401** [KATJ-HH2/katj#94]
## 버그 설명

[버그에 대한 명확하고 간결한 설명]
현준님이 작성한 testContainer 적용 후 github actions 실행 시 오류 발생

## 재현 단계

[버그를 재현하기 위한 단계]
예외가 발생하는 2가지 테스트 케이스에 @Disabled 없이 실행시 아래와 같은 오류 발생
![image](https://github.com/KATJ-HH2/katj/assets/87371627/2f14958e-a7a5-4f52-a829-d92219246742)

## 예상 동작

[예상했던 동작과 실제 동작의 차이]
github actions build test 정상 동작

2가지 테스트 케이스 @Disabled 적용시 정상 동작 확인

**Comment by JangHyeonJun2** [comment]
이거 어느 브랜치에요?
흠.. 어제 dev쪽 gradlew build, test 를 모두 확인을 했어가지구,, 브랜치 체크아웃 이후에 코드를 살펴봐야할거같네요.

**Comment by TonyKim9401** [comment]
@JangHyeonJun2 payment crd 브랜치 입니다 ㅜ

**Comment by JangHyeonJun2** [comment]
안녕하세요. @TonyKim9401 
해당 브랜치 체크아웃해서 확인해봤는데요. 이미 merge가 되어있어서 remote에서 체크아웃 하였습니다.

### 기존코드

```kotlin
@SpringBootTest
@TestConstructor(autowireMode = TestConstructor.AutowireMode.ALL)
class BillingServiceTest(
    private val billingService: BillingService,
    private val paymentMethodService: PaymentMethodService,
    private val paymentMethodRepository: PaymentMethodRepository,
    private val paymentMethodReader: PaymentMethodReader,
    private val userRepository: UserRepository,
    private val taxiRepository: TaxiRepository,
    private val taxiDriverRepository: TaxiDriverRepository,
    private val tripRepository: TripRepository,

){
   ...

  @Test
    fun `사용자가 기등록한 결제 정보가 하나도 없다`() {
        // given
        paymentMethodRepository.deleteAllInBatch()

        val driveStartAt = LocalDateTime.now().minusMinutes(20)
        val driveEndAt = LocalDateTime.now()
        val trip = Trip(
            user,
            taxiDriver,
            fare = 25000,
            departure = departure,
            destination = destination,
            driveStartDate = LocalDate.now(),
            driveStartAt = driveStartAt,
            driveEndDate = LocalDate.now(),
            driveEndAt = driveEndAt,
            spentTime = Duration.between(driveStartAt, driveEndAt).toMinutesPart(),
            tripStatus = TripStatus.PAY_REQUEST
        )

        // when // then
        assertThrows<DataNotFoundException> {
//            billingService.userPayWithRegiInfo(user.id, trip.id)
        }.apply {
            Assertions.assertThat(message).isEqualTo(ExceptionMessage.DUPLICATED_DATA_ALREADY_EXISTS.name)
        }

}
```


### 수정코드 
```kotlin
@KATJTestContainerE2E
class BillingServiceTest(
    private val billingService: BillingService,
    private val paymentMethodService: PaymentMethodService,
    private val paymentMethodRepository: PaymentMethodRepository,
    private val paymentMethodReader: PaymentMethodReader,
    private val userRepository: UserRepository,
    private val taxiRepository: TaxiRepository,
    private val taxiDriverRepository: TaxiDriverRepository,
    private val tripRepository: TripRepository,

): BaseTestEnitity(){
   ....
   @Test
    fun `사용자가 기등록한 결제 정보가 하나도 없다`() {
        // given
        paymentMethodRepository.deleteAllInBatch()

        val driveStartAt = LocalDateTime.now().minusMinutes(20)
        val driveEndAt = LocalDateTime.now()
        val trip = Trip(
            user,
            taxiDriver,
            fare = 25000,
            departure = departure,
            destination = destination,
            driveStartDate = LocalDate.now(),
            driveStartAt = driveStartAt,
            driveEndDate = LocalDate.now(),
            driveEndAt = driveEndAt,
            spentTime = Duration.between(driveStartAt, driveEndAt).toMinutesPart(),
            tripStatus = TripStatus.PAY_REQUEST
        )

        // when // then
        Assertions.assertThatThrownBy {
            billingService.userPayWithRegiInfo(user.id, trip.id)
        }.isInstanceOf(IllegalArgumentException::class.java)
    }

}

```

### 원인
- 테스트코드 사용법이 상이했습니다. `@KATJTESTConatinerE2E` 어노테이션을 사용하지 않으셨네요.
- BaseTestEntity()를 상속받으셔야했는데 받지않으셨더라구요.
- `사용자가 기등록한 결제 정보가 하나도 없다` 테스트 코드는 ./gradlew test 커맨드 뿐 아니라 Intelij 에서 돌렸을 때도 실패가 나더라구요.
   코드를 조금 수정하니 정상으로 떨어졌습니다.


#### 결과 attachment
<img width="1314" alt="스크린샷 2023-10-12 00 57 36" src="https://github.com/KATJ-HH2/katj/assets/38535971/b251f0df-4afe-43f6-8eb4-af0e34cb90e3">

**Comment by JangHyeonJun2** [comment]
안녕하세요. @Yoojin-An @jiseongTak 다른분들도 그 테스트코드에 사용되는 어노테이션 및 상속 클래스 한번 더 확인 부탁드립니다.

**Comment by TonyKim9401** [comment]
> 안녕하세요. @TonyKim9401 해당 브랜치 체크아웃해서 확인해봤는데요. 이미 merge가 되어있어서 remote에서 체크아웃 하였습니다.
> 
> ### 기존코드
> ```kotlin
> @SpringBootTest
> @TestConstructor(autowireMode = TestConstructor.AutowireMode.ALL)
> class BillingServiceTest(
>     private val billingService: BillingService,
>     private val paymentMethodService: PaymentMethodService,
>     private val paymentMethodRepository: PaymentMethodRepository,
>     private val paymentMethodReader: PaymentMethodReader,
>     private val userRepository: UserRepository,
>     private val taxiRepository: TaxiRepository,
>     private val taxiDriverRepository: TaxiDriverRepository,
>     private val tripRepository: TripRepository,
> 
> ){
>    ...
> 
>   @Test
>     fun `사용자가 기등록한 결제 정보가 하나도 없다`() {
>         // given
>         paymentMethodRepository.deleteAllInBatch()
> 
>         val driveStartAt = LocalDateTime.now().minusMinutes(20)
>         val driveEndAt = LocalDateTime.now()
>         val trip = Trip(
>             user,
>             taxiDriver,
>             fare = 25000,
>             departure = departure,
>             destination = destination,
>             driveStartDate = LocalDate.now(),
>             driveStartAt = driveStartAt,
>             driveEndDate = LocalDate.now(),
>             driveEndAt = driveEndAt,
>             spentTime = Duration.between(driveStartAt, driveEndAt).toMinutesPart(),
>             tripStatus = TripStatus.PAY_REQUEST
>         )
> 
>         // when // then
>         assertThrows<DataNotFoundException> {
> //            billingService.userPayWithRegiInfo(user.id, trip.id)
>         }.apply {
>             Assertions.assertThat(message).isEqualTo(ExceptionMessage.DUPLICATED_DATA_ALREADY_EXISTS.name)
>         }
> 
> }
> ```
> 
> ### 수정코드
> ```kotlin
> @KATJTestContainerE2E
> class BillingServiceTest(
>     private val billingService: BillingService,
>     private val paymentMethodService: PaymentMethodService,
>     private val paymentMethodRepository: PaymentMethodRepository,
>     private val paymentMethodReader: PaymentMethodReader,
>     private val userRepository: UserRepository,
>     private val taxiRepository: TaxiRepository,
>     private val taxiDriverRepository: TaxiDriverRepository,
>     private val tripRepository: TripRepository,
> 
> ): BaseTestEnitity(){
>    ....
>    @Test
>     fun `사용자가 기등록한 결제 정보가 하나도 없다`() {
>         // given
>         paymentMethodRepository.deleteAllInBatch()
> 
>         val driveStartAt = LocalDateTime.now().minusMinutes(20)
>         val driveEndAt = LocalDateTime.now()
>         val trip = Trip(
>             user,
>             taxiDriver,
>             fare = 25000,
>             departure = departure,
>             destination = destination,
>             driveStartDate = LocalDate.now(),
>             driveStartAt = driveStartAt,
>             driveEndDate = LocalDate.now(),
>             driveEndAt = driveEndAt,
>             spentTime = Duration.between(driveStartAt, driveEndAt).toMinutesPart(),
>             tripStatus = TripStatus.PAY_REQUEST
>         )
> 
>         // when // then
>         Assertions.assertThatThrownBy {
>             billingService.userPayWithRegiInfo(user.id, trip.id)
>         }.isInstanceOf(IllegalArgumentException::class.java)
>     }
> 
> }
> ```
> 
> ### 원인
> * 테스트코드 사용법이 상이했습니다. `@KATJTESTConatinerE2E` 어노테이션을 사용하지 않으셨네요.
> * BaseTestEntity()를 상속받으셔야했는데 받지않으셨더라구요.
> * `사용자가 기등록한 결제 정보가 하나도 없다` 테스트 코드는 ./gradlew test 커맨드 뿐 아니라 Intelij 에서 돌렸을 때도 실패가 나더라구요.
>   코드를 조금 수정하니 정상으로 떨어졌습니다.
> 
> #### 결과 attachment
> <img alt="스크린샷 2023-10-12 00 57 36" width="1314" src="https://user-images.githubusercontent.com/38535971/274343381-b251f0df-4afe-43f6-8eb4-af0e34cb90e3.png">

오류가 났던데 이게 아닌데 ㅜㅜ.. 이건 제가 방금막 올려둔거고 오류 났던건 PaymentMethodServiceTest 쪽 이였어요..
BillingService는 작성 막 시작한거라 dev쪽에 올릴 생각 없었는데 올라갔나요;
BillingService는 문제 나는게 맞습니다.. 정상 동작 확인 안해서요;

**Comment by JangHyeonJun2** [comment]
> payment crd 브랜치 입니다 ㅜ

해당 브랜치에서 났다고하셨지 않나요??

**Comment by jiseongTak** [comment]
@JangHyeonJun2  현준님 이거 로컬에서 테스트할때 추가로 설정해야되는게 있나요?

**Comment by JangHyeonJun2** [comment]
> @JangHyeonJun2 현준님 이거 로컬에서 테스트할때 추가로 설정해야되는게 있나요?

local에 src/test/resources에 application-test.yml 파일을 만드시고

```
spring:
  datasource:
    url: jdbc:tc:mysql:8.0.32:///katj
    username: katj
    password: katj123!
    driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver
  jpa:
    hibernate:
      ddl-auto: create-drop
```

해당 코드 기입하시면 됩니다. 요거 공유내용을 깜빡했네요. 죄송함돠🤦🏻

**Comment by jiseongTak** [comment]
> > @JangHyeonJun2 현준님 이거 로컬에서 테스트할때 추가로 설정해야되는게 있나요?
> 
> local에 src/test/resources에 application-test.yml 파일을 만드시고
> 
> ```
> spring:
>   datasource:
>     url: jdbc:tc:mysql:8.0.32:///katj
>     username: katj
>     password: katj123!
>     driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver
>   jpa:
>     hibernate:
>       ddl-auto: create-drop
> ```
> 
> 해당 코드 기입하시면 됩니다. 요거 공유내용을 깜빡했네요. 죄송함돠🤦🏻

넵 감사합니다!
