### ISSUE TITLE
trip 테이블 spentTime 자료형에 대한 고민

### ISSUE THREAD

**Issue by TonyKim9401** [KATJ-HH2/katj#95]
## 기능 제안

[제안하는 기능에 대한 명확하고 간결한 설명]
driveEndAt - driveStartAt 의 결과는 Int 값이 나오게 되는데
trip 테이블의 spentTime의 자료형은 LocalDateTime으로 되어 있음

## 예상 동작

[새로운 기능이 추가되면 어떻게 동작해야 하는지 설명]
총 소요시간 계산 후 저장시 자료형을 Int로 가져가야 한다고 생각됨
필요시 시간,분,초 정도로 계산하는 메서드 정도는 구현 필요성이 있다고 봄

## 추가 정보

[기능 제안에 대한 추가적인 정보나 컨텍스트]

**Comment by anewjean** [comment]
그렇다면 spentTime은 int로 변경하는게 좋을 것 같습니다!

**Comment by TonyKim9401** [comment]
확인했습니다!
